### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [isuke/droolmaw#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by isuke** [comment]
ok

I'll do it!

**Comment by isuke** [comment]
https://github.com/isuke/droolmaw/blob/main/README.md

DONE!
